//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseConditionClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHouseConditionService")]
    public interface IHouseConditionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHouseConditionService/GetTotalCosts", ReplyAction="http://tempuri.org/IHouseConditionService/GetTotalCostsResponse")]
        System.Nullable<decimal> GetTotalCosts();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHouseConditionServiceChannel : HouseConditionClient.ServiceReference1.IHouseConditionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HouseConditionServiceClient : System.ServiceModel.ClientBase<HouseConditionClient.ServiceReference1.IHouseConditionService>, HouseConditionClient.ServiceReference1.IHouseConditionService {
        
        public HouseConditionServiceClient() {
        }
        
        public HouseConditionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HouseConditionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HouseConditionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HouseConditionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Nullable<decimal> GetTotalCosts() {
            return base.Channel.GetTotalCosts();
        }
    }
}
