//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace HousingConditionPhoneApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHouseConditionService")]
    public interface IHouseConditionService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHouseConditionService/GetTotalCosts", ReplyAction="http://tempuri.org/IHouseConditionService/GetTotalCostsResponse")]
        System.IAsyncResult BeginGetTotalCosts(System.AsyncCallback callback, object asyncState);
        
        System.Nullable<decimal> EndGetTotalCosts(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHouseConditionServiceChannel : HousingConditionPhoneApp.ServiceReference1.IHouseConditionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTotalCostsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTotalCostsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Nullable<decimal> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Nullable<decimal>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HouseConditionServiceClient : System.ServiceModel.ClientBase<HousingConditionPhoneApp.ServiceReference1.IHouseConditionService>, HousingConditionPhoneApp.ServiceReference1.IHouseConditionService {
        
        private BeginOperationDelegate onBeginGetTotalCostsDelegate;
        
        private EndOperationDelegate onEndGetTotalCostsDelegate;
        
        private System.Threading.SendOrPostCallback onGetTotalCostsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public HouseConditionServiceClient() {
        }
        
        public HouseConditionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HouseConditionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HouseConditionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HouseConditionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetTotalCostsCompletedEventArgs> GetTotalCostsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HousingConditionPhoneApp.ServiceReference1.IHouseConditionService.BeginGetTotalCosts(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTotalCosts(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Nullable<decimal> HousingConditionPhoneApp.ServiceReference1.IHouseConditionService.EndGetTotalCosts(System.IAsyncResult result) {
            return base.Channel.EndGetTotalCosts(result);
        }
        
        private System.IAsyncResult OnBeginGetTotalCosts(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((HousingConditionPhoneApp.ServiceReference1.IHouseConditionService)(this)).BeginGetTotalCosts(callback, asyncState);
        }
        
        private object[] OnEndGetTotalCosts(System.IAsyncResult result) {
            System.Nullable<decimal> retVal = ((HousingConditionPhoneApp.ServiceReference1.IHouseConditionService)(this)).EndGetTotalCosts(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTotalCostsCompleted(object state) {
            if ((this.GetTotalCostsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTotalCostsCompleted(this, new GetTotalCostsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTotalCostsAsync() {
            this.GetTotalCostsAsync(null);
        }
        
        public void GetTotalCostsAsync(object userState) {
            if ((this.onBeginGetTotalCostsDelegate == null)) {
                this.onBeginGetTotalCostsDelegate = new BeginOperationDelegate(this.OnBeginGetTotalCosts);
            }
            if ((this.onEndGetTotalCostsDelegate == null)) {
                this.onEndGetTotalCostsDelegate = new EndOperationDelegate(this.OnEndGetTotalCosts);
            }
            if ((this.onGetTotalCostsCompletedDelegate == null)) {
                this.onGetTotalCostsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTotalCostsCompleted);
            }
            base.InvokeAsync(this.onBeginGetTotalCostsDelegate, null, this.onEndGetTotalCostsDelegate, this.onGetTotalCostsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override HousingConditionPhoneApp.ServiceReference1.IHouseConditionService CreateChannel() {
            return new HouseConditionServiceClientChannel(this);
        }
        
        private class HouseConditionServiceClientChannel : ChannelBase<HousingConditionPhoneApp.ServiceReference1.IHouseConditionService>, HousingConditionPhoneApp.ServiceReference1.IHouseConditionService {
            
            public HouseConditionServiceClientChannel(System.ServiceModel.ClientBase<HousingConditionPhoneApp.ServiceReference1.IHouseConditionService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetTotalCosts(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetTotalCosts", _args, callback, asyncState);
                return _result;
            }
            
            public System.Nullable<decimal> EndGetTotalCosts(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Nullable<decimal> _result = ((System.Nullable<decimal>)(base.EndInvoke("GetTotalCosts", _args, result)));
                return _result;
            }
        }
    }
}
