//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseConditionConsoleClient.HouseCondition {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HouseCondition.IHouseCondition")]
    public interface IHouseCondition {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHouseCondition/GetTotalCosts", ReplyAction="http://tempuri.org/IHouseCondition/GetTotalCostsResponse")]
        System.Nullable<decimal> GetTotalCosts();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHouseConditionChannel : HouseConditionConsoleClient.HouseCondition.IHouseCondition, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HouseConditionClient : System.ServiceModel.ClientBase<HouseConditionConsoleClient.HouseCondition.IHouseCondition>, HouseConditionConsoleClient.HouseCondition.IHouseCondition {
        
        public HouseConditionClient() {
        }
        
        public HouseConditionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HouseConditionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HouseConditionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HouseConditionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Nullable<decimal> GetTotalCosts() {
            return base.Channel.GetTotalCosts();
        }
    }
}
